apiVersion: ran.openshift.io/v1 
kind: SiteConfig
metadata:
  name: "gitopssno"
  namespace: "gitopssno"
spec:
  baseDomain: "tltlab.ericsson.se"
  pullSecretRef:
    name: "gitopssno-image-pull-secret"
  clusterImageSetNameRef: "openshift-4.10.0"
  sshPublicKey: ""
  clusters:
  - clusterName: "gitopssno"
    networkType: "OVNKubernetes"
    clusterLabels:
        common-4-9: true
        group-du-sno: ""
        sites: gitopssno
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 10.20.0.0/24
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - 0.rhel.pool.ntp.org
    # Optionally; This can be used to override the KlusterletAddonConfig that is creted for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "vdusno.gitopssno.tltlab.ericsson.se"
        role: "master"
        bmcAddress: "idrac-virtualmedia://172.16.1.20/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "acmsno-bmc-secret"
        bmcDisableCertificateVerification: true
        bootMACAddress: "e4:43:4b:fa:d8:ac"
        bootMode: UEFI
        rootDeviceHints:
          deviceName: "/dev/sdb"
#        cpuset: "0-1,30-33,62-63"
        nodeNetwork:
          interfaces:
            - name: eno2
              macAddress: "e4:43:4b:fa:d8:ac"
          config:
            interfaces:
              - name: eno2
                type: ethernet
                state: up
                macAddress: "e4:43:4b:fa:d8:ac"
                ipv4:
                  enabled: true
                  dhcp: true
                ipv6:
                  enabled: false
    
