apiVersion: v1
kind: Namespace
metadata:
  name: vdu-sno-policies
  labels:
    name: vdu-sno-policies
---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "vdu-sno"
  namespace: "vdu-sno-policies"
spec:
  bindingRules:
    sites: "gitopssno"
  mcp: "master"
  sourceFiles:
  
  #Create SRIOV policies
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-f1-policy"
      metadata:
        name: "pci-sriov-net-f1"
      spec:
        resourceName: pci_sriov_net_f1
          # nodeSelector:
            # node-role.kubernetes.io/master: ""
#        mtu: 1500
        numVfs: 8
        deviceType: netdevice
        nicSelector:
          # vendor: "8086"
          # deviceID: "1593"
          pfNames: ["ens1f0#0-5"]
        priority: 10
        isRdma: false
        linkType: eth
        
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-llscm-policy"
      metadata:
        name: "pci-sriov-net-llsm1"
      spec:
        resourceName: pci_sriov_net_llsm1
          # nodeSelector:
            # node-role.kubernetes.io/master: ""
#        mtu: 1500
        numVfs: 8
        deviceType: netdevice
        nicSelector:
          # vendor: "8086"
          # deviceID: "1593"
          pfNames: ["ens1f1#0-5"]
        priority: 10
        isRdma: false
        linkType: eth
        
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-llscu-policy"
      metadata:
        name: "pci-sriov-net-llscu1"
      spec:
        resourceName: pci_sriov_net_llscu1
          # nodeSelector:
            # node-role.kubernetes.io/master: ""
#        mtu: 1500
        numVfs: 8
        deviceType: vfio-pci
        nicSelector:
          # vendor: "8086"
          # deviceID: "1593"
          pfNames: ["ens1f1#6-7"]
        priority: 10
        isRdma: false
        linkType: eth
      
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-oam-policy"
      metadata:
        name: "pci-sriov-net-oam"
      spec:
        resourceName: pci_sriov_net_oam
          # nodeSelector:
            # node-role.kubernetes.io/master: ""
#        mtu: 1500
        numVfs: 8
        deviceType: netdevice
        nicSelector:
          # vendor: "8086"
          # deviceID: "1593"
          pfNames: ["ens1f0#6-7"]
        priority: 10
        isRdma: false
        linkType: eth
        
  #Create SRIOV network config
    - fileName: SriovNetwork.yaml
      policyName: "sriov-f1c-config"
      metadata:
        name: "networking-f1c"
      spec:
        ipam: |-
          {
            "type": "static",
            "addresses": [{"address": "10.114.120.180/26", "gateway": "10.114.120.129"}]
          }
        capabilities: '{ "ips": true }'
        resourceName: pci_sriov_net_f1
        networkNamespace: vdu
        vlan: 550
        linkState: auto
    
    - fileName: SriovNetwork.yaml
      policyName: "sriov-f1u-config"
      metadata:
        name: "networking-f1u"
      spec:
        ipam: |-
          {
            "type": "static",
            "addresses": [{"address": "10.114.120.134/26", "gateway": "10.114.120.129"}]
          }
        capabilities: '{ "ips": true }'
        resourceName: pci_sriov_net_f1
        networkNamespace: vdu
        vlan: 550
        linkState: auto
        
        
    - fileName: SriovNetwork.yaml
      policyName: "sriov-llscu1-config"
      metadata:
        name: "networking-llscu1"
      spec:
        resourceName: pci_sriov_net_llscu1
        networkNamespace: vdu
        linkState: auto
        spoofChk: "off"
        
    - fileName: SriovNetwork.yaml
      policyName: "sriov-llsm1-config"
      metadata:
        name: "networking-llsm1"
      spec:
        ipam: |-
          {
            "type": "static"
          }
        capabilities: '{ "mac": true, "ips": true }'
        resourceName: pci_sriov_net_llsm1
        networkNamespace: vdu
        linkState: auto
        vlan: 10 
                
        
    - fileName: PerformanceProfile.yaml
      policyName: "pao-profile-policy"
      metadata:
        name: performance
      spec:
        additionalKernelArgs:
        - "nohz_full=5-11"
        - "rcupdate.rcu_normal_after_boot=0"
        - "idle=poll"
        - "intel_iommu=on iommu=pt"
        cpu:
        #Used by application pods
          isolated: 7-70
        #Used by infra container
          reserved: 0-6
        globallyDisableIrqLoadBalancing: "false"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 32              
        machineConfigPoolSelector:
            pools.operator.machineconfiguration.openshift.io/master: ""
        nodeSelector:
            node-role.kubernetes.io/master: ""
        numa:
            topologyPolicy: "single-numa-node"
        realTimeKernel:
    #set it as true for 4.9.6+ to enable the rt kernel
            enabled: true
              
    # - fileName: TunedPerformancePatch.yaml
      # policyName: "tuned-perf-patch-policy"
      # spec:
        # profile:
          # - name: performance-patch
            # data: |
              # [main]
              # summary=Configuration changes profile inherited from performance created tuned
              # include=openshift-node-performance-openshift-node-performance-profile
              # [bootloader]
              # cmdline_crash=nohz_full=2-19,22-39
              # [sysctl]
              # kernel.timer_migration=1
              # [service]
              # service.stalld=start,enable
