apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: httpd-build
  labels:
    app: httpd-build
spec:
  source:
    type: Git
    git:
      uri: https://github.com/alam2018/acm_ztp
    contextDir: http_hub_cluster
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile    # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
  output:
    to:
      kind: ImageStreamTag
      name: httpd:latest