# test-sno-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace test-sno
apiVersion: v1
kind: Namespace
metadata:
  name: gitopssno
  labels:
    name: gitopssno
---

apiVersion: ran.openshift.io/v1 
kind: SiteConfig
metadata:
  name: "gitopssno"
  namespace: "gitopssno"
spec:
  baseDomain: "tltlab.ericsson.se"
  pullSecretRef:
    name: "gitopssno-image-pull-secret"
  clusterImageSetNameRef: "openshift-4.11.4"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQUpRM7zCaT6s058wJOXqS6vevBvxYYGB+XXu/4A67XN1NbX/byi8GezB9tT1dDopxI9bBW5LD/3lGvrlA64CHzeJACItkedXYqjHP0j++34G71Z8CiECdmyJjLtiO6OXxWPwDDq6EkmF0S8uf8TPeEpuC70DS7JittdXbRpRDFaCEum8SxtI3NWGCdfJkKQGKHyD15hsXMdMkf2nl+VjPpJXqnXA251/IWbbDQBesRj1iJmq5SYXWrQvg064nJtPXDo4ok8iH+DyT97QMZ19TyL4oqcytipY7ov/d/q8h0kf6wcKfK4s2pZhd4h2kzNjfOrQ71jJNsk/NAEsrtg5ZX9bE8BEittJIvcXZjDLtTKih9ZP41GAlfikYHf4Nkbd7DmfkTTweArm8cR8HLguhIISixaRhpH4WFTFYx6TyZek5RIHAxJETFCi3PBcVCHxGhjp3yLDKabp9aIFq2wruecHQR5FXe3BCazRILgPKk8F9akOQfEphO4vsdNGyw/E= edalaam@hds1.localdomain"
  clusters:
  - clusterName: "gitopssno"
    networkType: "OVNKubernetes"
    clusterType: sno
    clusterProfile: du
    clusterLabels:
        common: true
        group-du-sno: "group-du"
        sites: gitopssno
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 10.20.0.0/24
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - 0.rhel.pool.ntp.org
    # Optionally; This can be used to override the KlusterletAddonConfig that is creted for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "vdusno.gitopssno.tltlab.ericsson.se"
        role: "master"
        bmcAddress: "idrac-virtualmedia+https://172.16.1.20/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "gitopssno-bmc-secret"
#        disableCertificateVerification: True
        bootMACAddress: "e4:43:4b:fa:d8:ac"
        bootMode: UEFI
        rootDeviceHints:
          deviceName: "/dev/sdb"
#        cpuset: "0-1,30-33,62-63"
        nodeNetwork:
          interfaces:
            - name: eno2
              macAddress: "e4:43:4b:fa:d8:ac"
          config:
            interfaces:
              - name: eno2
                type: ethernet
                state: up
                macAddress: "e4:43:4b:fa:d8:ac"
                ipv4:
                  enabled: true
                  dhcp: true
                ipv6:
                  enabled: false
    
