# ---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common"
  namespace: "ztp-common"

spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    common: "true"
  sourceFiles:
    # SRIOV install
    - fileName: SriovSubscription.yaml
      policyName: "sriov-subscriptions-policy"
    - fileName: SriovSubscriptionNS.yaml
      policyName: "sriov-subscriptions-policy"
    - fileName: SriovSubscriptionOperGroup.yaml
      policyName: "sriov-subscriptions-policy"
    - fileName: SriovOperatorStatus.yaml
      policyName: "sriov-subscriptions-policy"
      
    #PTP install
    - fileName: PtpSubscription.yaml
      policyName: "ptp-subscriptions-policy"
    - fileName: PtpSubscriptionNS.yaml
      policyName: "ptp-subscriptions-policy"
    - fileName: PtpSubscriptionOperGroup.yaml
      policyName: "ptp-subscriptions-policy"
    - fileName: PtpOperatorStatus.yaml
      policyName: "ptp-subscriptions-policy"
    # - fileName: ClusterLogNS.yaml
      # policyName: "subscriptions-policy"
    # - fileName: ClusterLogOperGroup.yaml
      # policyName: "subscriptions-policy"
    # - fileName: ClusterLogSubscription.yaml
      # policyName: "subscriptions-policy"
    # - fileName: ClusterLogOperatorStatus.yaml
      # policyName: "subscriptions-policy"
      
    #Storage Install
    - fileName: StorageNS.yaml
      policyName: "storage-subscriptions-policy"
    - fileName: StorageOperGroup.yaml
      policyName: "storage-subscriptions-policy"
    - fileName: StorageSubscription.yaml
      policyName: "storage-subscriptions-policy"
    - fileName: StorageOperatorStatus.yaml
      policyName: "storage-subscriptions-policy"
      
    # FEC
    - fileName: AcceleratorsNS.yaml
      policyName: "sriov-fec-policy"
    - fileName: AcceleratorsOperGroup.yaml
      policyName: "sriov-fec-policy"
    - fileName: AcceleratorsSubscription.yaml
      policyName: "sriov-fec-policy"  
      
      
      
      
    # - fileName: ReduceMonitoringFootprint.yaml
      # policyName: "storage-config-policy"
    #
    # These CRs are in support of installation from a disconnected registry
    #
    # - fileName: OperatorHub.yaml
      # policyName: "config-policy"
    # - fileName: DefaultCatsrc.yaml
      # policyName: "config-policy"
      # # The Subscriptions all point to redhat-operators. The OperatorHub CR
      # # disables the defaults and this CR replaces redhat-operators with a
      # # CatalogSource pointing to the disconnected registry. Including both of
      # # these in the same policy orders their application to the cluster.
      # metadata:
        # name: redhat-operators
      # spec:
        # displayName: disconnected-redhat-operators
        # image: registry.example.com:5000/disconnected-redhat-operators/disconnected-redhat-operator-index:v4.9
    # - fileName: DisconnectedICSP.yaml
      # policyName: "config-policy"
      # spec:
        # repositoryDigestMirrors:
        # - mirrors:
          # - registry.example.com:5000
          # source: registry.redhat.io
          
          
         
