apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "vdu-sno"
  namespace: "ztp-site"
spec:
  remediationAction: enforce
  bindingRules:
    sites: "gitopssno"
  mcp: "master"
  sourceFiles:
  
  # #Create Local Storage Localvolume
    # - fileName: local-storage-local-volume.yaml
      # policyName: "localvolume-config-policy"
  
  
  #Create SRIOV policies
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-f1-policy"
      metadata:
        name: "pci-sriov-net-f1"
      spec:
        resourceName: pci_sriov_net_f1
          # nodeSelector:
            # node-role.kubernetes.io/master: ""
#        mtu: 1500
        numVfs: 8
        deviceType: netdevice
        nicSelector:
          # vendor: "8086"
          # deviceID: "1593"
          pfNames: ["ens1f0#0-5"]
        priority: 10
        isRdma: false
        linkType: eth
        
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-llscm-policy"
      metadata:
        name: "pci-sriov-net-llsm1"
      spec:
        resourceName: pci_sriov_net_llsm1
          # nodeSelector:
            # node-role.kubernetes.io/master: ""
#        mtu: 1500
        numVfs: 8
        deviceType: netdevice
        nicSelector:
          # vendor: "8086"
          # deviceID: "1593"
          pfNames: ["ens1f1#0-5"]
        priority: 10
        isRdma: false
        linkType: eth
        
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-llscu-policy"
      metadata:
        name: "pci-sriov-net-llscu1"
      spec:
        resourceName: pci_sriov_net_llscu1
          # nodeSelector:
            # node-role.kubernetes.io/master: ""
#        mtu: 1500
        numVfs: 8
        deviceType: vfio-pci
        nicSelector:
          # vendor: "8086"
          # deviceID: "1593"
          pfNames: ["ens1f1#6-7"]
        priority: 10
        isRdma: false
        linkType: eth
      
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-oam-policy"
      metadata:
        name: "pci-sriov-net-oam"
      spec:
        resourceName: pci_sriov_net_oam
          # nodeSelector:
            # node-role.kubernetes.io/master: ""
#        mtu: 1500
        numVfs: 8
        deviceType: netdevice
        nicSelector:
          # vendor: "8086"
          # deviceID: "1593"
          pfNames: ["ens1f0#6-7"]
        priority: 10
        isRdma: false
        linkType: eth
        
  #Create SRIOV network config
    - fileName: SriovNetwork.yaml
      policyName: "sriov-f1c-config"
      metadata:
        name: "networking-f1c"
      spec:
        ipam: |-
          {
            "type": "static",
            "addresses": [{"address": "10.114.120.180/26", "gateway": "10.114.120.129"}]
          }
        capabilities: '{ "ips": true }'
        resourceName: pci_sriov_net_f1
        networkNamespace: vdu
        vlan: 550
        linkState: auto
    
    - fileName: SriovNetwork.yaml
      policyName: "sriov-f1u-config"
      metadata:
        name: "networking-f1u"
      spec:
        ipam: |-
          {
            "type": "static",
            "addresses": [{"address": "10.114.120.134/26", "gateway": "10.114.120.129"}]
          }
        capabilities: '{ "ips": true }'
        resourceName: pci_sriov_net_f1
        networkNamespace: vdu
        vlan: 550
        linkState: auto
        
        
    - fileName: SriovNetwork.yaml
      policyName: "sriov-llscu1-config"
      metadata:
        name: "networking-llscu1"
      spec:
        resourceName: pci_sriov_net_llscu1
        networkNamespace: vdu
        linkState: auto
        spoofChk: "off"
        
    - fileName: SriovNetwork.yaml
      policyName: "sriov-llsm1-config"
      metadata:
        name: "networking-llsm1"
      spec:
        ipam: |-
          {
            "type": "static"
          }
        capabilities: '{ "mac": true, "ips": true }'
        resourceName: pci_sriov_net_llsm1
        networkNamespace: vdu
        linkState: auto
        vlan: 10 
                
    
    #Create performance profile    
    - fileName: PerformanceProfile.yaml
      policyName: "pao-profile-policy"
      metadata:
          name: performance
      spec:
          additionalKernelArgs:
          - nmi_watchdog=0
          - audit=0
          - mce=off
          - processor.max_cstate=1
          - nohz_full=2-23,26-47
          - rcupdate.rcu_normal_after_boot=0
          - idle=poll
          - intel_iommu=on iommu=pt
          cpu:
            isolated: 2-23,26-47
            reserved: 0-1,24-25
          globallyDisableIrqLoadBalancing: false
          hugepages:
            defaultHugepagesSize: 1G
            pages:
              - count: 32
                size: 1G
          machineConfigPoolSelector:
            pools.operator.machineconfiguration.openshift.io/master: ""
          nodeSelector:
            node-role.kubernetes.io/master: ""
          numa:
            topologyPolicy: single-numa-node
          realTimeKernel:
            enabled: true
            globallyDisableIrqLoadBalancing: false
          workloadHints:
            highPowerConsumption: true
            realTime: true


            
    #Disable Chronyd
    - fileName: MachineConfigDisableChronyd.yaml
      policyName: "mc-chronyd-policy"
      metadata:
          labels:
            machineconfiguration.openshift.io/role: master
          name: disable-chronyd
      spec:
          config:
            ignition:
              version: 3.2.0
            systemd:
              units:
                - contents: |
                    [Unit]
                    Description=NTP client/server
                    Documentation=man:chronyd(8) man:chrony.conf(5)
                    After=ntpdate.service sntp.service ntpd.service
                    Conflicts=ntpd.service systemd-timesyncd.service
                    ConditionCapability=CAP_SYS_TIME
                    [Service]
                    Type=forking
                    PIDFile=/run/chrony/chronyd.pid
                    EnvironmentFile=-/etc/sysconfig/chronyd
                    ExecStart=/usr/sbin/chronyd $OPTIONS
                    ExecStartPost=/usr/libexec/chrony-helper update-daemon
                    PrivateTmp=yes
                    ProtectHome=yes
                    ProtectSystem=full
                    [Install]
                    WantedBy=multi-user.target
                  enabled: false
                  name: "chronyd.service"
      
    # # PTP config
    # - fileName: PtpConfigSlave.yaml
      # policyName: "ptp-config-policy"
      # metadata:
        # name: "du-ptp-slave"
      # spec:
        # profile:
        # - name: "crdu-ptp"
    # #    interface: "ens1f0"    # Change to host interface name
          # interface: ""
          # ptp4lOpts: "-2"
          # phc2sysOpts: "-a -r -n 24 -u 2"
          # ptpSchedulingPolicy: SCHED_FIFO
          # ptpSchedulingPriority: 10
          # ptp4lConf: |
              # [ens1f0]
              # masterOnly 0
              # [ens1f1]
              # masterOnly 1
              # [global]
              # #
              # # Default data set
              # #
              # twoStepFlag 1
              # #slaveOnly 1
              # priority1 128
              # priority2 128
              # domainNumber 24
              # #utc_offset 37
              # clockClass 248
              # clockAccuracy 0xFE
              # offsetScaledLogVariance 0xFFFF
              # free_running 0
              # freq_est_interval 1
              # dscp_event 0
              # dscp_general 0
              # dataset_comparison G.8275.x
              # G.8275.defaultDS.localPriority 128
              # #
              # # Port data set
              # #
              # logAnnounceInterval -3
              # logSyncInterval -4
              # logMinDelayReqInterval -4
              # logMinPdelayReqInterval -4
              # announceReceiptTimeout 3
              # syncReceiptTimeout 0
              # delayAsymmetry 0
              # fault_reset_interval 4
              # neighborPropDelayThresh 20000000
              # masterOnly 0
              # G.8275.portDS.localPriority 128
              # #
              # # Runtime options
              # #
              # assume_two_step 0
              # logging_level 6
              # path_trace_enabled 0
              # follow_up_info 0
              # hybrid_e2e 0
              # inhibit_multicast_service 0
              # net_sync_monitor 0
              # tc_spanning_tree 0
              # tx_timestamp_timeout 50
              # unicast_listen 0
              # unicast_master_table 0
              # unicast_req_duration 3600
              # use_syslog 1
              # verbose 0
              # summary_interval -4
              # kernel_leap 1
              # check_fup_sync 0
              # #
              # # Servo options
              # #
              # pi_proportional_const 0.0
              # pi_integral_const 0.0
              # pi_proportional_scale 0.0
              # pi_proportional_exponent -0.3
              # pi_proportional_norm_max 0.7
              # pi_integral_scale 0.0
              # pi_integral_exponent 0.4
              # pi_integral_norm_max 0.3
              # step_threshold 30.0
              # first_step_threshold 0.00002
              # max_frequency 900000000
              # clock_servo pi
              # sanity_freq_limit 200000000
              # ntpshm_segment 0
              # #
              # # Transport options
              # #
              # transportSpecific 0x0
              # ptp_dst_mac 01:1B:19:00:00:00
              # p2p_dst_mac 01:80:C2:00:00:0E
              # udp_ttl 1
              # udp6_scope 0x0E
              # uds_address /var/run/ptp4l
              # #
              # # Default interface options
              # #
              # clock_type OC
              # network_transport UDPv4
              # delay_mechanism E2E
              # time_stamping hardware
              # tsproc_mode filter
              # delay_filter moving_median
              # delay_filter_length 10
              # egressLatency 0
              # ingressLatency 0
              # boundary_clock_jbod 1
              # #
              # # Clock description
              # #
              # productDescription ;;
              # revisionData ;;
              # manufacturerIdentity 00:00:00
              # userDescription ;
              # timeSource 0xA0
        # recommend:
        # - profile: "crdu-ptp"
          # priority: 4
          # match:
          # - nodeLabel: "node-role.kubernetes.io/master"
            # nodeName: "sno"    # Change to CR DU node name
              
